require(htmlwidgets)

#' Display trees in 3D visualization
#'
#' Trees object should be generated by generate_trees()
#'
#' @import htmlwidgets
#'
#' @export
vtree <- function(trees, setting = list(), width = NULL, height = NULL, elementId = NULL) {

  # forward options using x
  x = list(
    trees = trees,
    setting = setting
  )

  # create widget
  htmlwidgets::createWidget(
    name = 'vtree',
    x,
    width = width,
    height = height,
    package = 'vtree',
    elementId = elementId
  )
}

#' Shiny bindings for vtree
#'
#' Output and render functions for using vtree within Shiny
#' applications and interactive Rmd documents.
#'
#' @param outputId output variable to read from
#' @param width,height Must be a valid CSS unit (like \code{'100\%'},
#'   \code{'400px'}, \code{'auto'}) or a number, which will be coerced to a
#'   string and have \code{'px'} appended.
#' @param expr An expression that generates a vtree
#' @param env The environment in which to evaluate \code{expr}.
#' @param quoted Is \code{expr} a quoted expression (with \code{quote()})? This
#'   is useful if you want to save an expression in a variable.
#'
#' @name vtree-shiny
#'
#' @export
vtreeOutput <- function(outputId, width = '100%', height = '400px'){
  htmlwidgets::shinyWidgetOutput(outputId, 'vtree', width, height, package = 'vtree')
}

#' @rdname vtree-shiny
#' @export
renderVtree <- function(expr, env = parent.frame(), quoted = FALSE) {
  if (!quoted) { expr <- substitute(expr) } # force quoted
  htmlwidgets::shinyRenderWidget(expr, vtreeOutput, env, quoted = TRUE)
}
